### ISSUE TITLE
Create checklist form for Airport Challenge

### ISSUE THREAD

**Issue by silvabox** [makersacademy/airport_challenge#179]
Google Form to allow reviewers to mark issues they find so coaches can aggregate the results and know which areas to cover in more detail

**Comment by tansaku** [comment]
first prototype: https://docs.google.com/forms/d/1_QJxz8Twnc28e5wyVpB6xmXCvP3M_HPUXk65EGLhiZw/viewform

**Comment by tansaku** [comment]
TODO: add comment field and reverse link to docs in repo
