### ISSUE TITLE
Hound and Rubocop have differing agendas

### ISSUE THREAD

**Issue by sanjsanj** [makersacademy/airport_challenge#4]
@tansaku  @MihaiLiviuCojocar  @nikeshashar   G'Morning guys, just wanted to let you know that Hound throws an error when quoting strings with single quotes and Rubocop when using double quotes, I'll continue to see if there's a solution to please both of them.

Also my code is very badly designed but I'll refactor this weekend.

**Comment by armi1189** [comment]
Yeah i've noticed that too. Hope that there's a solution, in the meantime i'll stick with Rubocop standards, so my Raketests won't fail just for double quotes.

cheers!

**Comment by tansaku** [comment]
Yeah, rubocops dog is being a bit overexcited there.

I'll be muzzling him Monday morning.

Personally I prefer to use single quotes wherever possible following my "least power principle" 

Cheers, Sam 

iPhoneから送信

22 Mar 2015 13:33、Andrea Armiliato <notifications@github.com> のメッセージ:
